# Generated by Django 4.2.5 on 2023-10-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_title_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.TextField(),
        ),
    ]
