# Generated by Django 4.2.5 on 2023-10-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_community_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default='none'),
        ),
    ]
