# Generated by Django 4.2.5 on 2023-10-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_post_caption_alter_post_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='post_images'),
        ),
    ]
