# Generated by Django 4.2.5 on 2023-10-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_comment_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
